//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveDots {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewerRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewerRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveDots.ViewerRES", typeof(ViewerRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string Do_blanca {
            get {
                return ResourceManager.GetString("Do blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1/2.
        /// </summary>
        internal static string Do_corchea {
            get {
                return ResourceManager.GetString("Do corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string Do_negra {
            get {
                return ResourceManager.GetString("Do negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4.
        /// </summary>
        internal static string Do_redonda {
            get {
                return ResourceManager.GetString("Do redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        internal static string Fa_blanca {
            get {
                return ResourceManager.GetString("Fa blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1/2.
        /// </summary>
        internal static string Fa_corchea {
            get {
                return ResourceManager.GetString("Fa corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string Fa_negra {
            get {
                return ResourceManager.GetString("Fa negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        internal static string Fa_redonda {
            get {
                return ResourceManager.GetString("Fa redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        internal static string La_blanca {
            get {
                return ResourceManager.GetString("La blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1/2.
        /// </summary>
        internal static string La_corchea {
            get {
                return ResourceManager.GetString("La corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        internal static string La_negra {
            get {
                return ResourceManager.GetString("La negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string La_redonda {
            get {
                return ResourceManager.GetString("La redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E2.
        /// </summary>
        internal static string Mi_blanca {
            get {
                return ResourceManager.GetString("Mi blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1/2.
        /// </summary>
        internal static string Mi_corchea {
            get {
                return ResourceManager.GetString("Mi corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1.
        /// </summary>
        internal static string Mi_negra {
            get {
                return ResourceManager.GetString("Mi negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E4.
        /// </summary>
        internal static string Mi_redonda {
            get {
                return ResourceManager.GetString("Mi redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2.
        /// </summary>
        internal static string Re_blanca {
            get {
                return ResourceManager.GetString("Re blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1/2.
        /// </summary>
        internal static string Re_corchea {
            get {
                return ResourceManager.GetString("Re corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1.
        /// </summary>
        internal static string Re_negra {
            get {
                return ResourceManager.GetString("Re negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D4.
        /// </summary>
        internal static string Re_redonda {
            get {
                return ResourceManager.GetString("Re redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2.
        /// </summary>
        internal static string Si_blanca {
            get {
                return ResourceManager.GetString("Si blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1/2.
        /// </summary>
        internal static string Si_corchea {
            get {
                return ResourceManager.GetString("Si corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        internal static string Si_negra {
            get {
                return ResourceManager.GetString("Si negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4.
        /// </summary>
        internal static string Si_redonda {
            get {
                return ResourceManager.GetString("Si redonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G2.
        /// </summary>
        internal static string Sol_blanca {
            get {
                return ResourceManager.GetString("Sol blanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G1/2.
        /// </summary>
        internal static string Sol_corchea {
            get {
                return ResourceManager.GetString("Sol corchea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G1.
        /// </summary>
        internal static string Sol_negra {
            get {
                return ResourceManager.GetString("Sol negra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G4.
        /// </summary>
        internal static string Sol_redonda {
            get {
                return ResourceManager.GetString("Sol redonda", resourceCulture);
            }
        }
    }
}
