//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveDots {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewerRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewerRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveDots.ViewerRES", typeof(ViewerRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La negra.
        /// </summary>
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La corchea.
        /// </summary>
        internal static string A1_2 {
            get {
                return ResourceManager.GetString("A1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La blanca.
        /// </summary>
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La redonda.
        /// </summary>
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si negra.
        /// </summary>
        internal static string B1 {
            get {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si corchea.
        /// </summary>
        internal static string B1_2 {
            get {
                return ResourceManager.GetString("B1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si blanca.
        /// </summary>
        internal static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si redonda.
        /// </summary>
        internal static string B4 {
            get {
                return ResourceManager.GetString("B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do negra.
        /// </summary>
        internal static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do corchea.
        /// </summary>
        internal static string C1_2 {
            get {
                return ResourceManager.GetString("C1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do blanca.
        /// </summary>
        internal static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do redonda.
        /// </summary>
        internal static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re negra.
        /// </summary>
        internal static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re corchea.
        /// </summary>
        internal static string D1_2 {
            get {
                return ResourceManager.GetString("D1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re blanca.
        /// </summary>
        internal static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re redonda.
        /// </summary>
        internal static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi negra.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi corchea.
        /// </summary>
        internal static string E1_2 {
            get {
                return ResourceManager.GetString("E1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi blanca.
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi redonda.
        /// </summary>
        internal static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa negra.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa corchea.
        /// </summary>
        internal static string F1_2 {
            get {
                return ResourceManager.GetString("F1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa blanca.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa redonda.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol negra.
        /// </summary>
        internal static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol corchea.
        /// </summary>
        internal static string G1_2 {
            get {
                return ResourceManager.GetString("G1/2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol blanca.
        /// </summary>
        internal static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol redonda.
        /// </summary>
        internal static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
    }
}
